### ISSUE TITLE
Displays wrong time on days of the year that go from regular time to DST or the opposite way

### ISSUE THREAD

**Issue by ruurd** [N00bySumairu/SmoothAnalogClock.widget#2]
https://github.com/N00bySumairu/SmoothAnalogClock.widget/blob/09ff295d569e7da6a78c38c469b225944d9ad294/SmoothAnalogClock.widget/index.coffee#L66

Since that will span DST changes that will yield an error (running an hour fast today in NL)
Make that:

```
date   = new Date()
hours = date.getHours();
minutes = date.getMinutes();
seconds = date.getSeconds();

time = hours * 60 * 60 * 1000 + minutes * 60 * 1000 + seconds * 1000;
```

**Comment by hcsch** [comment]
Nice too see that people are still using this ^^

If that is alright with you I'd just use your suggested code (albeit a little adapted) and I'll add a comment in the README.MD about how this issue was found and the solution suggested by you. (i.e. your code falls under the same MIT license as the rest of the code, but it gets a mention).

A small heads up: I no longer own a Mac and as such I am also no longer using Übersicht. I'll probably archive this repo after this issue is resolved. Feel free to fork it though. If you'd like I could also transfer the repo to you.

**Comment by N00bySumairu** [comment]
Hey, nice to see that people are still using this ^^

If that is alright with you I'd just use your code (albeit a little modified) and I'll add a notice to the `README.MD` about how you found the issue and suggested the change. (i.e. your code would fall under the same MIT license as the rest of the code, but you'd get a mention).

A small heads up: I no longer own a Mac and as such I also no longer use Übersicht. I'll probably archive this repository after this issue is resolved. If you'd like I could also transfer the repo to you.

**Comment by ruurd** [comment]
I'm fine with that. No problem. I'd be happy to maintain it - I think I will be using Macs for some time :-)

**Comment by N00bySumairu** [comment]
Alright, then I'll push the fix now and transfer ownership to you :)

**Comment by ruurd** [comment]
Top! 👍

**Comment by hcsch** [comment]
I have initiated the transfer. You might have to update the data about the widget's repo on the Übersicht website. And you should probably change the widget metadata to your name & email for the author ^^

**Comment by ruurd** [comment]
I'll talk to the Übersicht guy. He's a Dutchie too...

**Comment by N00bySumairu** [comment]
Sweet, thanks for that (btw. sorry about the deleted comment... I may or may not have written that with the wrong account)

**Comment by ruurd** [comment]
Transferred all in good order. No need to worry about that comment - you have been very forthcoming.
